<?php


/**
 * Implements hook_block_info().
 */
function dolce_user_links_block_info() {
    $blocks['dolce_user_links'] = array(
        'info' => t('Dolce - User Links'),
        'title' => '',
        'region' => 'header',
        'cache' => DRUPAL_NO_CACHE,
    );

    $blocks['dolce_user_links_logout'] = array(
        'info' => t('Dolce - User Links logout'),
        'title' => '',
    );

    $blocks['dolce_user_links_addressbook'] = array(
        'info' => t('Dolce - User Links Addressbook'),
        'title' => '',
    );

    $blocks['dolce_user_links_profile'] = array(
        'info' => t('Dolce - User Links Profile'),
        'title' => '',
    );

    $blocks['dolce_user_links_goback_account'] = array(
        'info' => t('Dolce - User Links Goback account'),
        'title' => '',
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dolce_user_links_block_view($delta = '') {
    global $user;
    $uid = $user->uid;
    switch ($delta) {
        case 'dolce_user_links':
            return array(
                'subject' => t('Dolce - User Links'),
                'content' => theme(
                    'dolce_user_links',
                    array(
                        'links' =>_dolce_user_links_data()
                    )
                ),
            );
            break;
        case 'dolce_user_links_logout':
            return array(
                'subject' => t('Dolce - User Links logout'),
                'content' => _dolce_user_logout_data(),
            );
            break;
        case 'dolce_user_links_addressbook':
            return array(
                'subject' => t('Dolce - User Links Addressbook'),
                'content' => _dolce_user_links_addressbook_data(),
            );
            break;
        case 'dolce_user_links_goback_account':
            return array(
                'subject' => t('Dolce - User Links Gobackaccount'),
                'content' => _dolce_user_user_profile_data(),
            );
            break;
        case 'dolce_user_links_profile':
            return array(
                'subject' => t('Dolce - User Links Profile'),
                'content' => theme(
                    'dolce_user_links_inside',
                    array(
                        'data' => _dolce_user_links_profile_data(),
                    )
                ),
            );
            break;
    }
}

/**
 * Implements hook_theme().
 */
function dolce_user_links_theme($existing, $type, $theme, $path) {
    return array(
        'dolce_user_links' => array(
            'template' => 'dolce_user_links',
            'arguments' => array('links' => array())
        ),
        'dolce_user_links_inside' => array(
            'template' => 'dolce_user_links_inside',
            'arguments' => array('data' => array())
        ),
    );
}

/**
 * Retrieve the current customers lightweight shopping cart data.
 */
function _dolce_user_links_data() {
    $links = array();
    global $user;
    if (user_is_anonymous()) {
        $links = array(
            'class' => 'login',
            'href' => 'user/login',
            'title' => t('My account'),
        );
    }
    else {
        $links = array(
            'class' => 'login-connected',
            'href' => 'user',
            'title' => t('My account'),
        );
    }

    return $links;
}

/**
 * Retrieve the current disconnected links
 */
function _dolce_user_logout_data() {
    $links = array();
    global $user;
    $html = '<div class="dolce-user-links-logout-wrapper">';
    $prefix = '<i class="fas fa-sign-out-alt"></i> ';
    $html .= l($prefix.t('Logout'), 'user/logout', array('html' => true, 'attributes' => array('class' => 'dolce-user-logout')));
    $html .= '</div>';
    return $html;
}

/**
 * Retrieve the current disconnected links
 */
function _dolce_user_links_addressbook_data() {
    global $user;
    $uid = $user->uid;

    $html = '<div class="dolce-user-links-addressbook-wrapper">';

    $prefix = '<i class="fas fa-money-bill"></i> ';

    $html .= l($prefix. t('Billing information'),  'user/'.$uid.'/addressbook/billing', array('html' => true, 'attributes' => array('class' => array('dolce-user-links-addressbook-billing'))));

    $prefix = '<i class="fas fa-shipping-fast"></i> ';
    $html .= l($prefix. t('Shipping information'),  'user/'.$uid.'/addressbook/billing', array('html' => true, 'attributes' => array('class' => array('dolce-user-links-addressbook-billing'))));


    $html .= '</div>';

    return $html;
}


/**
 * Retrieve the current customers links in the profile
 */
function _dolce_user_links_profile_data() {
    global $user;
    $args = arg();
    $uid = $args[1];
    global $language;
    $profile = array(
        'infos' => array(
          'link' => url("user/$uid/edit", array('absolute' => TRUE, 'language' => $language)),
          'icon' => 'far fa-4x fa-user-circle',
          'class' => 'informations',
          'text' => t('My informations'),
        ),
        'addresses' => array(
        'link' => url("user/$uid/addressbook", array('absolute' => TRUE, 'language' => $language)),
        'icon' => 'far fa-4x fa-address-book',
        'class' => 'addresses',
        'text' => t('My addresses'),
        ),
        'orders' => array(
        'link' => url("user/$uid/orders", array('absolute' => TRUE, 'language' => $language)),
        'icon' => 'fas fa-4x fa-file-invoice',
        'class' => 'orders',
        'text' => t('My orders'),
        ),

    );
      if (user_access('access dolce event')) {
        $profile['events'] = array(
          'link' => url("event/turid-rugaas-2021", array('absolute' => TRUE, 'language' => $language)),
          'icon' => 'fa fa-4x fa-film',
          'class' => 'events',
          'text' => t('Turid Rugaas Seminar'),
      );
    }
    return $profile;
}

function _dolce_user_user_profile_data() {
    $links = array();
    global $user;
    $html = '<div class="dolce-user-links-profile-wrapper">';
    $prefix = '<i class="far fa-user-circle"></i> ';
    $html .= l($prefix.t('Go back to my account'), 'user', array('html' => true, 'attributes' => array('class' => 'dolce-user-profile')));
    $html .= '</div>';
    return $html;
}
