<?php

function dolce_enig_form($form, &$form_state) {

  $form['box-container'] = array(
    '#prefix' => '<div id="enigma">',
  );

  $form['message'] = array(
    '#markup' => NULL,
  );

  if (variable_get('dolce_event_seminar_day') == '20') {
    $numLetters = 6;
  }
  else if (variable_get('dolce_event_seminar_day') == '21') {
    $numLetters = 7;
    $form['clues']= array(
      '#markup' => '<div class="clue-wrapper">'._get_img_clue(1)._get_img_clue(2)._get_img_clue(3).'</div>'
    );
  }
  for ($i=1;$i<=$numLetters;$i++) {
    $form['letter'.$i] = array(
      '#type' => 'textfield',
      '#size' => 1,
      '#title' => NULL,
      '#maxlength' => 1,
      '#required' => TRUE,
      '#attributes' => array('placeholder' => t('_')),
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '<i class="fas fa-trophy"></i> '. t("Check if you won"),
    '#ajax' => array(
      'callback' => 'dolce_enig_ajax_submit_callback',
      'wrapper' => 'enigma',
    ),
    '#attributes' => array('class' => array('btn btn-primary')),
    '#suffix' => '</div>',
  );

  $form['#attached']['css'][] = drupal_get_path('module', 'dolce_enig').'/css/dolce_enig.css';

  return $form;
}


function dolce_enig_ajax_submit_callback($form, &$form_state) {
  global $user;
  $nextone = '';
  $day = variable_get('dolce_event_seminar_day');
  if ($day == '20') {
    $numLetters = 6;
    $correct = array(
      'letter1' => 's',
      'letter2' => 'n',
      'letter3' => 'o',
      'letter4' => 'o',
      'letter5' => 'p',
      'letter6' => 'y',
    );
  }
  else if ($day == '21') {
    $numLetters = 7;
    $correct = array(
      'letter1' => 'h',
      'letter2' => 'a',
      'letter3' => 'c',
      'letter4' => 'h',
      'letter5' => 'i',
      'letter6' => 'k',
      'letter7' => 'o',
    );
  }

  for ($i=1; $i<=$numLetters; $i++) {
    $letter = strtolower(trim($form_state['values']['letter'.$i]));
    if ($letter == $correct['letter'.$i]) {
      $answer = true;
    }
    else {
      $answer = false;
      break;
    }
  }
  if ($answer == true) {
    $already_winner = variable_get('dolce_enig_winner_'.$day, NULL);
    if (!empty($already_winner)) {
      $message = t('Well done ! But someone has been quicker than you !'). ' ';
      //Pas de lot de consolation pour le jour 2
      $nextone = t('You can ask for your gift here: ').l(t('Fill the form'), '/node/158', array('attributes' => array('target' => '_blank')));
    }
    else {
      variable_set('dolce_enig_winner_'.$day, $user->uid);
      $message = t('<i class="fas fa-trophy"></i> Well done ! You are the winner of the game! You will be contacted very soon by our team!');
    }
  }
  //Si mauvais reponse
  else {
    $message = t('Oops ! You can try again :) ');
  }

  $element = $form;
  $element['message']['#markup'] = '<div id="messages">'.$message.$nextone.'</div>';
  return $element;

}

/**
* Implements hook_block_info().
*/

function dolce_enig_block_info() {
  $blocks['dolce_enigma_paw'] = array(
    'info' => t('Dolce - Paw Enigma'),
    'title' => '',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/

function dolce_enig_block_view($delta = '') {
  switch ($delta) {
    case 'dolce_enigma_paw':
    return array(
      'subject' => t('Dolce - Paw Enigma'),
      'content' => array(
        '#markup' => theme('dolce_enig_paw', array('data' => dolce_enig_get_data())),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module','dolce_enig').'/css/dolce_enig.css',
          ),
          'js' => array(
            drupal_get_path('module','dolce_enig').'/js/dolce_enig.js',
          ),
        ),
      ),
    );
    break;
  }
}

function dolce_enig_theme($existing, $type, $theme, $path) {
  return array(
    'dolce_enig_paw' => array(
      'template' => 'dolce_enig_paw',
      'arguments' => array('data' => array()),
    ),
  );
}

function dolce_enig_get_data() {
  return array(
    'day' => variable_get('dolce_event_seminar_day'),
    'imgClue' => _get_img_clue(0),
  );
}
function _get_img_clue($num) {
  $alt_title = t('This is a clue ! ');
  $path = drupal_get_path('module', 'dolce_enig').'/img/clue'.$num.'.png';
  $variables = array(
    'path' => $path,
    'alt' => $alt_title,
    'title' => $alt_title,
    'width' => '50%',
    'height' => '50%',
    'attributes' => array('class' => 'img-enigma-clue'),
  );
  $img = theme('image', $variables);
  return $img;
}
