<?php

/**
 * Implements hook_module_implements_alter().
 */
function dolce_user_module_implements_alter(&$implementations, $hook) {
    if ($hook == 'form_alter') {
        // Move my_module_rdf_mapping() to the end of the list. module_implements()
        // iterates through $implementations with a foreach loop which PHP iterates
        // in the order that the items were added, so to move an item to the end of
        // the array, we remove it and then add it.
        $group = $implementations['dolce_user'];
        unset($implementations['dolce_user']);
        $implementations['dolce_user'] = $group;
    }
}

/**
 * Implements hook_form_alter().
 */
function dolce_user_form_alter(&$form, &$form_state, $form_id) {

    if ($form_id == 'user_login') {
        $form['name']['#prefix']  = '<div id="' . $form_id . '_form">';
        $form['name']['#prefix'] .= '<h1>' . t('Login') . '</h1>';
        $form['pass']['#suffix'] = l(t('Forgot your password?'), 'user/password', array('attributes' => array('class' => array('login-password'), 'title' => t('Get a new password'))));
        $form['actions']['#suffix']  = '</div>';
        if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL) != USER_REGISTER_ADMINISTRATORS_ONLY) {
            $form['actions']['#suffix'] .= '<div class="create-account clearfix">';
            $form['actions']['#suffix'] .= "\r<h2>" . t('I don\'t have an account') . "</h2>";
            $form['actions']['#suffix'] .= "\r" . l(t('Create an account'), 'user/register', array('attributes' => array('class' => array('btn btn-primary login-register'), 'title' => t('Create a new account'))));
            $form['actions']['#suffix'] .= '</div>';
        }
    }
    if ($form_id == 'user_pass') {
        $form['name']['#prefix'] = '<div id="' . $form_id . '_form">';
        $form['name']['#prefix'] .= '<h1>' . t('Request a new password') . '</h1>';
        $form['actions']['#suffix'] = '<div class="back-to-login clearfix">' . l(t('Back to login'), 'user/login', array('attributes' => array('class' => array('login-account'), 'title' => t('Sign in')))) . '</div>';
        $form['actions']['#suffix'] .= '</div>';
    }
    if ($form_id == 'user_register_form') {
        $form['account']['name']['#prefix'] = '<div id="' . $form_id . '">';
        $form['account']['name']['#prefix'] .= '<h1>' . t('Register') . '</h1>';
        $form['actions']['submit']['#suffix'] = '<div class="back-to-login clearfix">' . l(t('Back to login'), 'user/login', array('attributes' => array('class' => array('login-account'), 'title' => t('Sign in')))) . '</div>';
        $form['actions']['submit']['#suffix'] .= '</div>';
    }
    if ($form_id == 'commerce_ajax_cart_form') {
        $form['empty']['#default_value'] = t('There is no product in your cart');
    }
    if ($form_id == 'commerce_addressbook_customer_profile_form') {
        if (!user_has_role(3)) {
            $form['commerce_customer_address']['und']['0']['country']['#options'] = array(
                'FR' => t("France"),
            );
        }
    }
}