<?php

/**
 * @file
 * Provides Kickstart-specific blocks and menus.
 */


/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function dolce_discount_block_info() {
    $blocks['shipping_discount'] = array(
        'info' => t('Shipping discount'),
        'weight' => '0',
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    $blocks['promotional_banner'] = array(
        'info' => t('Promotional banner'),
        'weight' => '0',
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function dolce_discount_block_view($delta = '') {
    $block = array(
        'subject' => NULL,
        'content' => NULL,
    );

    switch ($delta) {
        case 'shipping_discount':
            $amount = '4900';
            $items = array(
                commerce_kickstart_block_build_element(t('<span><em>Free</em> shipping</span> on orders over'), 'shipping_message'),
                commerce_kickstart_block_build_element(t('@amount', array('@amount' => commerce_currency_format($amount, commerce_default_currency()))), 'shipping_currency'),
            );
            $block['content'] = commerce_kickstart_block_build_element(implode('', $items), 'shipping', NULL, 'div');
            break;

        case 'promotional_banner':
            $block = module_invoke('jquery_countdown_timer', 'block_view', 'jquery_countdown_timer');
            $timer = render($block['content']);
            $items = array(
                commerce_kickstart_block_build_element(t('Joyeuses fêtes !'), NULL, 'promotional_banner_saving'),
                t("Les envois sont suspendus à partir du 19 décembre jusqu'au 3 janvier 2018"),
                //$timer,
                //commerce_kickstart_block_build_element(t('Joyeuses fêtes !'), NULL, 'promotional_banner_special_offer'),

            );
            $block['content'] = commerce_kickstart_block_build_element(implode(' ', $items), 'promotional_banner', NULL, 'div');
            break;
    }
    return $block;
}

/**
 * Implements hook_preprocess_page().
 */
function dolce_discount_preprocess_page(&$variables) {
    if (drupal_is_front_page()) {
        // Remove the title from this page.
        $variables['title'] = '';
    }
}

/**
 * Build an HTML element.
 *
 * @param $content
 *   The element contents.
 * @param $id
 *   The element id attribute.
 * @param $class
 *   The element class attribute.
 * @param $type
 *   The element type.
 *
 * @return
 *   The HTML element string.
 */
function dolce_discount_block_build_element($content, $id = NULL, $class = NULL, $type = 'span') {
    $id = $id ? "id=\"$id\"" : '';
    $class = $class ? "class=\"$class\"" : '';
    return "<$type $id $class>$content</$type>";
}
