<?php

function dolce_fees_node_view($node, $view_mode, $langcode){
    switch ($node->type) {
        case 'fees':
            $amount = $node->field_fees_price['und'][0]['value'] * 100;

            if (empty($_POST['stripeToken'])) {
                $script = '<form action="" method="POST"><script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_live_wK0D4tPk6U3Pl09CdyLzPgWy"
          data-amount="'.$amount.'"
          data-name="ToutPourMonChien"
          data-description="'.$node->title.'"
          data-image="https://www.dolcevitadog.com/sites/all/themes/dolce/logo.png"
          data-locale="auto"
          data-zip-code="false"
          data-currency="eur">
        </script></form>';
                $node->content['fees'] = array(
                    '#markup' => $script,
                    '#weight' => 10,
                );
            }
            else {

                //require_once('/var/www/tpmc/' . drupal_get_path('module', 'tpmc_reserv').'/stripe/lib/Stripe.php');
                //require_once('/var/www/tpmc/' . drupal_get_path('module', 'tpmc_reserv').'/stripe/lib/Charge.php');
                // See your keys here: https://dashboard.stripe.com/account/apikeys
                //\Stripe\Stripe::setApiKey("sk_test_R7NoPeIcKjgxUxWoMfYLvP1m");
                $token = $_POST['stripeToken'];
                exec('curl https://api.stripe.com/v1/charges \
   -u sk_live_ECBriOlLVIhqcTuusBeP2auW: \
   -d amount='.$amount.' \
   -d currency=eur \
   -d description="'.$node->title.'" \
   -d source='.$token);
                // Token is created using Stripe.js or Checkout!
                // Get the payment token ID submitted by the form:
                drupal_set_message('Votre paiement à bien été validé');
                // Charge the user's card:
                /*
                $charge = \Stripe\Charge::create(array(
                  "amount" => $amount,
                  "currency" => "eur",
                  "description" => $node->title,
                  "source" => $token,
                ));
                */
            }
    }
}