<?php

/**
 * Implements hook_menu().
 */
function dolce_se_menu()
{
    $items['admin/config/dolce-se'] = array(
        'title' => t('Configure Shipment estimation'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dolce_se_configure_form'),
        'access arguments' => array('administer site configuration'),
    );

    return $items;
}

function dolce_se_configure_form($form, $form_state)
{
    $form['dolce_se_text'] = array(
        '#type' => 'textarea',
        '#title' => t('Suffix text'),
        '#default_value' => variable_get('dolce_se_text', ''),
    );

    return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 */
function dolce_se_form_alter(&$form, &$form_state, $form_id) {
    switch ($form_id) {
        case 'commerce_checkout_form_shipping':

            $form['commerce_shipping']['dolce-se']['#markup'] = theme('dolce_se_theme', array('content' => dolce_se_get_estimated_date()));
            $form['commerce_shipping']['dolce-se']['#weight'] = 1;
    }
}

function dolce_se_theme($existing, $type, $theme, $path) {
    $items['dolce_se_theme'] = array(
        'template' => 'dolce_se_shipping_form',
        'arguments' => array('content' => array())
    );

    return $items;
}

/**
 * @return array
 * Calcule la date estimative de livraison
 */
function dolce_se_get_estimated_date() {
    $args = arg();
    $country =  _dolce_se_get_contry_by_order_id($args[1]);

 $date = new DateTime();
 $day = $date->format('l');
 if ($country != 'FR') {
     $country = 'OTHER';
 }
 $delay = add_days($country, $day);
 $date->add(new DateInterval('P'.$delay.'D'));
    setlocale (LC_TIME, 'fr_FR.utf8','fra');
    $format = 'd F Y';
    $estimated_date = _dolce_se_dateToFrench($date, $format);

 return array(
     'delivery_date' => $estimated_date,
     'dolce-se-text' => variable_get('dolce_se_text', '')
 );
}

function _dolce_se_dateToFrench($date, $format)
{
    $english_days = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
    $french_days = array('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche');
    $english_months = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
    $french_months = array('janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
    return str_replace($english_months, $french_months, str_replace($english_days, $french_days, $date->format($format) ) );
}

/* Temps de livraison selon le code pays */
function add_days($countryCode, $day) {
  /*
    $array =  array(
        'FR' => array(
            'Monday' => 4,
            'Tuesday' => 4,
            'Wednesday' => 4,
            'Thursday' => 4,
            'Friday' => 5,
            'Saturday' => 5,
            'Sunday' => 4,
        ),
        'OTHER' => array(
            'Monday' => 6,
            'Tuesday' => 6,
            'Wednesday' => 6,
            'Thursday' => 6,
            'Friday' => 8,
            'Saturday' => 8,
            'Sunday' => 7,
        ),
    );

  */
     $array =  array(
        'FR' => array(
            'Monday' => 6,
            'Tuesday' => 12,
            'Wednesday' => 11,
            'Thursday' => 10,
            'Friday' => 9,
            'Saturday' => 8,
            'Sunday' => 7,
        ),
        'OTHER' => array(
            'Monday' => 10,
            'Tuesday' => 16,
            'Wednesday' => 15,
            'Thursday' => 14,
            'Friday' => 13,
            'Saturday' => 12,
            'Sunday' => 11,
        ),
    );

    return $array[$countryCode][$day];
}

/* Retourne le country code de l'adresse de livraison pour une commande */
function _dolce_se_get_contry_by_order_id($order_id) {
    $order = commerce_order_load($order_id);
    $profile = commerce_customer_profile_load($order->commerce_customer_shipping['und']['0']['profile_id']);
    $country = $profile->commerce_customer_address['und']['0']['country'];
    if (!empty($country)) {
        return $country;
    }
    return NULL;
}
